name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push the Docker image for ubuntu 20.04
      env:
        cuda_versions: 11.0 11.1
      run: |
        for cuda_version in $cuda_versions; do 
          docker build ubuntu-desktop/20.04 --file Dockerfile  \
             --build-arg CUDAGL_VERSION=${cuda_version}-devel-ubuntu20.04 \
             --tag ubuntu-desktop:20.04-$cuda_version
          docker push ubuntu-desktop:20.04-${cuda_version}
        done
